# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: ST
tagline: ""
description: ""
url: https://tsaist1.github.io
baseurl: /

author:
  name: "ShengTse Tsai"
  url:

paginate: 5

github:
  repo: https://github.com/tsaist1/tsaist1.github.io

plugins: [jekyll-paginate]

include:
  - public
