# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: ST
email: shengtsetsai@gmail.com
description: ""
baseurl: /

author:
  name: "ShengTse Tsai"
  url: tsaist1.github.io

paginate: 5

# Custom vars
version: 2.1.0

github:
  repo:

plugins: [jekyll-paginate]
