# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: ST
tagline: ""
description: ""
url: https://tsais7.github.io
baseurl: /

author:
  name: "ShengTse Tsai"
  url: https://tsais7.github.io

paginate: 5

github: https://github.com/tsais7

plugins: [jekyll-paginate]

include:
  - public
