title: ShengTse Tsai blog 
email: shengtsetsai@gmail.com
description: "my lil pool of reading materials, rants and tidbits"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tsaist1.github.io"

# twitter_username: yourusername
github_username:  tsaist1

theme: hyde
plugins:
  - jekyll-feed